import shelve

#ficheiro que permite povoar a nossa "base de dados" que corresponde a um dicionário com chaves a referenciar cada relatorio e 
#cujo valor é também um dicionário com chaves que correspondem ao tipo, título, subtítulo, autores,conteúdo, conclusão, referências, etc.
s = shelve.open("relatorios.db")

s["relatorio1"] = {"tipo": 2, "title":"Comunicações e Redes", "subtitle":"TP1: Introdução à Internet e Comunicações por Satélite","iimage": "https://pplware.sapo.pt/wp-content/uploads/2019/12/internet_espaco00-720x383.jpg",
"authors": [["Marco Silva",85441,"marcosilva@gmail.com","930001110"],["José Ferreira",83899,"joseferreira@gmail.com","930001111"]],"masters":"Informática Médica 2019/2020",
"content":["Parte I - Internet, IETF e RFCs:A IETF é uma comunidade de nível internacional, a qual inclui um conjunto de designers, operadores, fornecedores e pesquisadores de redes cuja preocupação é a evolução da arquitetura da internet e o seu bom funcionamento. Encontra-se dividida em grupos de trabalho de acordo com a sua área de especialização, ou seja, transporte, segurança, tráfego de dados, distribuição de dados, etc… Todas estas áreas são administradas pelos respetivos diretores que são membros do IESG (Internet Engineering Steering Group). Este grupo é, de facto, o responsável pela gestão das atividades da IETF, pelo processo de padrões da Internet, o qual corresponde à aprovação final de especificações tais como padrões da Internet e a publicação de RFCs.O que são RFCs? Têm um formato geral comum?As RFCs (Request for Comments) são documentos desenvolvidos e mantidos por indivíduos e organizações que lidam com tecnologia. Um documento RFC poder ser, de facto, criado por diferentes organizações tais como: IETF (Internet Engineering Taskforce), IRTF (Internet Research Taskforce) ou IAB (Internet Architecture Board) e por diferentes autores independentes. Todo o eventual sistema que é capaz de analisar e criar as RFCs é sustentado pela Sociedade da Internet (ISOC – Internet Society). Todo o processo de desenvolvimento de um RFC está descrito no RFC 2026. Para se poder criar um RFC é necessário um documento rascunho, o Internet Draft(I-D), que é proposto para o IETF e, após uma votação e possível alteração, o IESG publica o documento como um RFC. Quando é que o IP foi introduzido pela primeira vez? O IP (Internet Protocol) foi inicialmente introduzido em 1983 na sua ligação com o protocolo TCP (Transmission Control Protocol), que é o protocolo standard o qual é usado na Internet nos dias de hoje. O protocolo IP é responsável pela comunicação entre hosts em redes TCP/IP, isto é, é o responsável pela comunicação entre cada elemento da rede para permitir o transporte de uma mensagem de um host de origem até um host de destino, podendo a mensagem passar por várias sub-redes.",
"Parte II - Comunicações por satélite: Os satélites Gorizont 29 e Nilesat 201 para além de apresentarem uma órbita geostacionária, isto é, uma órbita cujos pontos se repetem acima da Terra e ao longo do tempo, ( órbita acima da linha do equador ), apresentam um período de rotação à volta da Terra de, aproximadamente, 1440 minutos, tal como é evidenciado na tabela 1, que é equivalente ao período de rotação do planeta. Permitindo, assim, que sejam manuseados e utilizados em recursos tais como as comunicações a nível global, nomeadamente previsão da meteorologia e streaming ou broadcasting na televisão, computadores e telemóveis. Também podem ser usados para nível militar em campos da defesa e inteligência internacional."],
"image": "https://i.ibb.co/c3R888x/Foto1.png","conclusion":"Os satélites OBCOMM 15 e IRIDIUM 166 são de baixa altitude, pois apresentam uma órbita de altitude relativamente baixa, especialmente quando comparada com os satélites geostacionários. Como tal, apresentam características diferentes, isto é, passam pelos mesmos pontos do planeta Terra a diferentes horas do dia, designando-se, por satélites assíncronos e, portanto, a sua cobertura terrestre é, aproximadamente, global. Apresentam um atraso na sua transmissão muito menor, na ordem dos milissegundos. Também são satélites cujo custo é significativamente menor que os geostacionários, já que necessitam de menos energia para os colocar em órbita. As principais aplicações destes satélites são as comunicações móveis, tais como as comunicações sem fios que permitem a manutenção e a implementação dos sistemas distribuídos e a regularização e observação da atmosfera e superfície da Terra.",
"references":["https://www.ietf.org/","https://www.ietf.org/about/mission/","https://www.internetsociety.org/about-the-ietf/","https://canaltech.com.br/internet/O-que-e-um-RFC/"], "link":"https://drive.google.com/file/d/1CFtGqT9dPbLF89-1TDzhXTTlfC4_Uw7l/view?usp=sharing",
"description": ["Satélites"]} 

s["relatorio2"] = {"tipo": 2, "title":"Comunicações e Redes", "subtitle":"TP2: Caminhos e Atrasos da Internet","iimage": "https://yata.ostr.locaweb.com.br/f6e846f076ceaf07bed0a6fa12091c294fa045f88e98d6e65565bba38b3601a1",
"authors": [["Manuela Pereira",84331,"manuelapereira@gmail.com","930111110"],["Paula Mendes",84372,"paulamendes@gmail.com","960001111"]],"masters":"Informática Médica 2019/2020",
"content":["O Traceroute é uma ferramenta que permite observar a trajetória de um pacote de dados até um determinado host, permitindo a deteção de possíveis problemas de roteamento.O traceroute compila uma lista dos computadores na rede que estão envolvidos com uma atividade específica da Internet. Identifica cada computador/servidor nessa lista e a quantidade de tempo que os dados demoraram a ir de um computador para o outro. Se houver uma interrupção na transferência de dados, o traceroute mostrará onde, ao longo da cadeia, ocorreu o problema. De seguida, usando vários servidores externos, realizar-se-á um traceroute a dois IPs diferentes e comentar-se-ão os resultados.","193.136.9.240:",
"Centralops:Podemos observar que no início o rtt se encontra estável e sem saltos súbitos mostrando que a internet local se encontra sem problemas de latência. Por outro lado, no salto do hop 3 para 4 até ao 7 observamos que começam a aparecer o símbolo “*” e um aumento súbito do valor de rtt do hop 6/7 para o hop 8, mostrando que poderia ter acontecido uma das seguintes situações: houve perda do pacote de dados ou a resposta não retornou no tempo alocado para tal ou simplesmente porque houve um aumento no tráfego na ligação da Internet local ou porque o servidor poderia ter estado carregado de pedidos, todos ao mesmo tempo ou o router está num caminho configurado para não dar uma resposta, através de uma firewall. A mesma situação acontece desde o hop 10 a 12 e 19 a 21 pelas mesmas razões mencionadas anteriormente. Por fim, após 154 ms o pacote de dados chega ao destino e reenviado novamente para o IP inicial",
"Whatismyipadress:Com base no servidor externo “Whatismyipadress”, observamos que houve 21 saltos até chegar ao IP adress mencionado e para que tal acontecesse foram necessários 208.317 ms para o pacote de dados chegar e ser reenviado para o IP inicial. É de salientar que houve um aumento súbito do hop 6 para 7, mas cujo salto se manteve sensivelmente constante até ao destino, evidenciando que a ligação não teve problemas e que, por isso, pode ter sido resultado do facto dos pacotes do traceroute serem de baixa prioridade e que por isso podem ter ou não sido perdidos ou atrasados, numa grande ligação de Internet pública. Também é importante referir que não aparecem os hops 12 a 14. Tal significa o mesmo que o símbolo “*”. A razão por detrás deste símbolo poderão ser exatamente as mesmas mencionadas no ponto a).",
"As3257: Relativamente ao server externo As3257, observa-se que 12 saltos não suficientes para chegar ao IP mencionado. No entanto, podemos concluir à partida que o tempo de resposta será superior a 56.140 ms e que houve um aumento substancial do hop 8 até ao 12, evidenciando o símbolo “*”, uma vez que haverá grande possibilidade de ter havido perda do pacote de dados ou que simplesmente o tempo de resposta foi superior ao valor do tempo alocado para tal."],
"image": "https://i.ibb.co/pdb38xq/Traceroute-ao-IP-193-136-9-240-a-partir-do-Centralops-net.png","conclusion":"Conclui-se que não há qualquer semelhança entre eles. Além de não apresentarem o mesmo número de saltos, os caminhos são diferentes, não passando necessariamente pelos mesmos routers, uma vez que estamos a realizar o traceroute de um IP inicial para um IP final distintos.",
"references":["https://www.cloudflare.com/learning/cdn/glossary/round-trip-time-rtt/","https://www.inmotionhosting.com/support/website/ssh/read-traceroute/","https://www.xfinity.com/support/articles/run-traceroute-command"], "link":"https://drive.google.com/file/d/1TiBNFUOcjnmwWaWmvbE_I8itfmuB6o9b/view?usp=sharing",
"description": ["Atrasos na Internet"]} 

s["relatorio3"] = {"tipo": 1, "title":"Comunicações e Redes", "subtitle":"TP3: Transmissão de dados e Atrasos","iimage": "https://fabiobmed.com.br/wp-content/uploads/2012/04/transmiss%C3%A3o-de-dados.jpg",
"authors": [["Ricardo Pereira",84634,"ricardopereira@gmail.com","930001110"],["Maria Matos",83999,"mariamatos@gmail.com","930005555"]],"masters":"Informática Médica 2019/2020",
"introduction":"O processo de envio de pacotes está sujeito a atrasos, ocasionados por vários fatores. Há 4 tipos principais de atrasos: atraso de processamento, atraso de fila, atraso de transmissão e atraso de propagação.A soma dos atrasos dá-nos o atraso total. Quanto maior este valor, menor será a velocidade de transmissão de dados na rede.",
"questions":[["Inicialmente, suponha que há apenas um link entre a origem e o destino. Suponha que todo o arquivo MP3 seja enviado como um pacote. O atraso de transmissão é:","Resposta: 3 segundos","O atraso de transmissão calcula-se da seguinte forma:delay de transmissão=(tamanho do pacote)/(taxa de transmissão)=(30×10^6 bits)/(10×10^6 bits/s)=3s."],
["Referindo-se à pergunta acima, o atraso de ponta a ponta ( atraso de transmissão mais atraso de propagação ) é :","Resposta : 3.05 segundos","O atraso de propagação é obtido a partir da seguinte equação : delay de propagação = ( distância entre dois nós ) / ( velocidade de propagação ) = ( 10000 × 10^3 m ) / ( 2 × 10^8 m/s ) = 0.05 s. Como o valor de atraso de transmissão calculado anteriormente foi de 3s, logo o atraso total é a soma do atraso de propagação e o atraso de transmissão, ou seja, 3.05s."],
["Referindo-se à pergunta acima, quantos bits a fonte terá transmitido quando o primeiro bit chegar ao destino:","Resposta: 500000 bits","Quando o primeiro bit chegar ao destino irão ter ocorrido 0,5s, uma vez que esse bit necessita de 0,5s para se propagar da fonte para o destino. Durante esse tempo, é possível calcular o número de bits que a fonte poderá transmitir, visto que o atraso de transmissão calculado anteriormente corresponde aos 30 Mbit. Portanto, o número de bits transmitidos em 0,5s será: X=(0,05 × 30×10^6)/3=500000 bits."]],
"references":["https://docente.ifrn.edu.br/tadeuferreira/disciplinas/2012.2/redes-i-dependencia/Aula05.pdf"], "link":"https://drive.google.com/file/d/1_I0cienfur1eseU_ocTcRS0pLjGtTj5j/view?usp=sharing",
"description": ["Atrasos na Internet"]} 

s.close()