# Generated by Django 3.1.5 on 2021-01-31 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(null=True)),
                ('observacoes', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('morada', models.CharField(max_length=500)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('cc', models.CharField(max_length=12)),
                ('datanasc', models.DateField()),
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('numfunc', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('morada', models.CharField(max_length=500)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('cc', models.CharField(max_length=12)),
                ('datanasc', models.DateField()),
                ('id_gestor', models.AutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=14)),
                ('telefone_emergencia', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('dci', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('formafarmaceutica', models.CharField(max_length=200)),
                ('dosagem', models.CharField(max_length=200, null=True)),
                ('estadoautorizacao', models.CharField(max_length=200)),
                ('generico', models.BooleanField(default=True)),
                ('titular_aim', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id_medicao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('peso', models.DecimalField(decimal_places=5, max_digits=200)),
                ('glicemia', models.DecimalField(decimal_places=5, max_digits=200)),
                ('altura', models.IntegerField()),
                ('tensaoarterial', models.IntegerField()),
                ('colesterol', models.IntegerField()),
                ('trigliceridios', models.IntegerField()),
                ('saturacao', models.IntegerField()),
                ('inr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('morada', models.CharField(max_length=500)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('cc', models.CharField(max_length=12)),
                ('datanasc', models.DateField()),
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=200, unique=True)),
                ('especialidade', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('morada', models.CharField(max_length=500)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('cc', models.CharField(max_length=12)),
                ('datanasc', models.DateField()),
                ('id_utente', models.AutoField(primary_key=True, serialize=False)),
                ('numutente', models.CharField(max_length=200, unique=True)),
                ('telefone', models.CharField(max_length=14)),
                ('telefone_emergencia', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id_prescricao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('toma', models.CharField(max_length=200)),
                ('consulta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alves_lda.consulta')),
                ('med', models.ManyToManyField(to='alves_lda.Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_medica',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('historico', models.CharField(blank=True, max_length=2000)),
                ('medicoes', models.ManyToManyField(to='alves_lda.Medicao')),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alves_lda.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id_exame', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('duracao', models.TimeField()),
                ('preco', models.DecimalField(decimal_places=5, max_digits=200)),
                ('estado', models.BooleanField(max_length=200)),
                ('observacoes', models.CharField(max_length=200)),
                ('consulta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alves_lda.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada_Agenda',
            fields=[
                ('id_entradagenda', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alves_lda.medico')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alves_lda.utente')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='fichamedica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alves_lda.ficha_medica'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alves_lda.medico'),
        ),
    ]
